version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
  initiatiaves-backend:
    build:
      dockerfile: ./src/main/docker/Dockerfile
      context: .
    ports:
      - 8080:8080
    links:
      - mongodb
